DROP POLICY IF EXISTS members view their org ON public.organizations;
CREATE POLICY members view their org ON public.organizations FOR SELECT USING (is_org_member(auth.uid(), id)) ;
DROP POLICY IF EXISTS admins update their org ON public.organizations;
CREATE POLICY admins update their org ON public.organizations FOR UPDATE USING (has_role(auth.uid(), id, 'admin'::app_role)) ;
DROP POLICY IF EXISTS view org roles ON public.user_roles;
CREATE POLICY view org roles ON public.user_roles FOR SELECT USING (is_org_member(auth.uid(), organization_id)) ;
DROP POLICY IF EXISTS insert role self bootstrap ON public.user_roles;
CREATE POLICY insert role self bootstrap ON public.user_roles FOR INSERT  WITH CHECK ((user_user_id = auth.uid()));
DROP POLICY IF EXISTS admins manage roles ON public.user_roles;
CREATE POLICY admins manage roles ON public.user_roles  USING (has_role(auth.uid(), organization_id, 'admin'::app_role)) WITH CHECK (has_role(auth.uid(), organization_id, 'admin'::app_role));
DROP POLICY IF EXISTS Public Read ON public.categorias;
CREATE POLICY Public Read ON public.categorias FOR SELECT USING (true) ;
DROP POLICY IF EXISTS Public Read ON public.fornecedores;
CREATE POLICY Public Read ON public.fornecedores FOR SELECT USING (true) ;
DROP POLICY IF EXISTS Public Read ON public.itens_inventario;
CREATE POLICY Public Read ON public.itens_inventario FOR SELECT USING (true) ;
DROP POLICY IF EXISTS authenticated can create org ON public.organizations;
CREATE POLICY authenticated can create org ON public.organizations FOR INSERT  WITH CHECK ((auth.uid() IS NOT NULL));
DROP POLICY IF EXISTS profiles_self_all ON public.profiles;
CREATE POLICY profiles_self_all ON public.profiles  USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS profiles_admin_select ON public.profiles;
CREATE POLICY profiles_admin_select ON public.profiles FOR SELECT USING (is_admin()) ;
DROP POLICY IF EXISTS profiles_admin_manage ON public.profiles;
CREATE POLICY profiles_admin_manage ON public.profiles  USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS profiles_signup_insert ON public.profiles;
CREATE POLICY profiles_signup_insert ON public.profiles FOR INSERT  WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS Technician access chamados ON public.chamados;
CREATE POLICY Technician access chamados ON public.chamados FOR SELECT USING (is_tecnico()) ;
DROP POLICY IF EXISTS Technician update chamados ON public.chamados;
CREATE POLICY Technician update chamados ON public.chamados FOR UPDATE USING (is_tecnico()) ;
DROP POLICY IF EXISTS User view own chamados ON public.chamados;
CREATE POLICY User view own chamados ON public.chamados FOR SELECT USING ((usuario_user_id = auth.uid())) ;
DROP POLICY IF EXISTS User create own chamados ON public.chamados;
CREATE POLICY User create own chamados ON public.chamados FOR INSERT  WITH CHECK ((usuario_user_id = auth.uid()));
DROP POLICY IF EXISTS User update own chamados ON public.chamados;
CREATE POLICY User update own chamados ON public.chamados FOR UPDATE USING (((usuario_user_id = auth.uid()) AND (NOT is_tecnico()))) ;
DROP POLICY IF EXISTS System settings are viewable by authenticated users ON public.system_settings;
CREATE POLICY System settings are viewable by authenticated users ON public.system_settings FOR SELECT USING ((auth.role() = 'authenticated'::text)) ;
DROP POLICY IF EXISTS Users can insert interactions on their tickets ON public.comentarios_chamado;
CREATE POLICY Users can insert interactions on their tickets ON public.comentarios_chamado FOR INSERT  WITH CHECK ((EXISTS ( SELECT 1);
DROP POLICY IF EXISTS Users can view their own notifications ON public.notificacoes;
CREATE POLICY Users can view their own notifications ON public.notificacoes FOR SELECT USING ((my_id() = usuario_id)) ;
DROP POLICY IF EXISTS Users can update their own notifications ON public.notificacoes;
CREATE POLICY Users can update their own notifications ON public.notificacoes FOR UPDATE USING ((my_id() = usuario_id)) ;
DROP POLICY IF EXISTS Master users can manage all organizations ON public.organizations;
CREATE POLICY Master users can manage all organizations ON public.organizations  USING (check_is_master()) ;
DROP POLICY IF EXISTS Master users can manage all user_roles ON public.user_roles;
CREATE POLICY Master users can manage all user_roles ON public.user_roles  USING (check_is_master()) ;
DROP POLICY IF EXISTS Technicians view own schedules ON public.expedientes;
CREATE POLICY Technicians view own schedules ON public.expedientes FOR SELECT USING ((usuario_user_id = auth.uid())) ;
DROP POLICY IF EXISTS Anyone view active services ON public.servicos;
CREATE POLICY Anyone view active services ON public.servicos FOR SELECT USING ((ativo = true)) ;
DROP POLICY IF EXISTS Role definitions are viewable by all authenticated users ON public.role_definitions;
CREATE POLICY Role definitions are viewable by all authenticated users ON public.role_definitions FOR SELECT USING ((auth.role() = 'authenticated'::text)) ;
DROP POLICY IF EXISTS Users create comments on their tickets ON public.comentarios_chamado;
CREATE POLICY Users create comments on their tickets ON public.comentarios_chamado FOR INSERT  WITH CHECK ((EXISTS ( SELECT 1);
DROP POLICY IF EXISTS Users view own reimbursements ON public.reembolsos;
CREATE POLICY Users view own reimbursements ON public.reembolsos FOR SELECT USING ((solicitante_user_id = auth.uid())) ;
DROP POLICY IF EXISTS Users create reimbursements ON public.reembolsos;
CREATE POLICY Users create reimbursements ON public.reembolsos FOR INSERT  WITH CHECK ((solicitante_user_id = auth.uid()));
DROP POLICY IF EXISTS Everyone can view menu manuals ON public.help_menu_manuals;
CREATE POLICY Everyone can view menu manuals ON public.help_menu_manuals FOR SELECT USING (true) ;
DROP POLICY IF EXISTS Allow system to insert logs ON public.audit_logs;
CREATE POLICY Allow system to insert logs ON public.audit_logs FOR INSERT  WITH CHECK (true);